### ISSUE TITLE
Adapte code for Older version (Pre-12)

### ISSUE THREAD

**Issue by IkiaeM** [GIGABAIT-Official/WidgetPack#1]
Adapting the code in a new branch for an older version because Pre-13 changes a lot of things and some other modules are not updated yet so limits the possibility to switch to Pre-13, an adaptation would be cool if it doesn't require too much work.

**Comment by Sylensky** [comment]
I honestly think it does not make much sense to make the extra steps for a older version when the missing modules will be updated anyway sooner or later.

**Comment by PadowYT2** [comment]
We will not make pr12,
1. Reverting back is harder then upgrading
2. v2 is coming really soon
